latest changes

diff --git a/.github/workflows/deployment.yml b/.github/workflows/deployment.yml
--- a/.github/workflows/deployment.yml
+++ b/.github/workflows/deployment.yml
@@ -8,6 +8,7 @@ on:
 jobs:
   push-to-repo:
     runs-on: ubuntu-latest
+    environment: GITHUB_PUSH
     steps:
       - name: Checkout source repository
         uses: actions/checkout@v4
@@ -27,7 +28,17 @@ jobs:
           git config user.name "Ali Hyder"
           git config user.email "cw.alihyder@gmail.com"
 
+      - name: Create temporary directory excluding deployment.yml
+        run: |
+          mkdir temp-repo
+          rsync -av --exclude='.github/workflows/deployment.yml' --exclude='.git' ./ temp-repo/
+          cd temp-repo
+          git init
+          git add .
+          git commit -m "Latest Changes"
+
       - name: Push to target repository
         run: |
+          cd temp-repo
           git remote add target git@github.com:remlyo-ai/remlyo-backend.git
-          git push target main --force  # Adjust branch as needed
+          git push target main --force || { echo "Push failed"; exit 1; }
